# Where the arenas will be
World: gg_arenas

# What players can join arenas when they are running
# And have them start with only themselves in it
OverridePlayers:
  - johncorby
  - funkymunky111

# Do not touch these
Lobby: []
Arenas: []
